import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { toast } from "sonner";
import { useMemo, useState } from "react";
import { Check, X, Wallet, Globe, Users, Receipt, RefreshCcw, Settings, Search, ShieldCheck, CreditCard, Plus, Trash2, Pencil, Upload } from "lucide-react";
import { StatusBadge } from "@/components/dashboard/StatusBadge";

export default function AdminPanel() {
  const { user, loading } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/" });
  const { data, isLoading, refetch } = trpc.admin.overview.useQuery(undefined, { enabled: user?.role === "admin" });
  const [tab, setTab] = useState<"overview"|"purchases"|"deposits"|"users"|"sites"|"payments"|"settings">("overview");
  const [reason, setReason] = useState("");
  const [selected, setSelected] = useState<number|null>(null);
  const approvePurchase = trpc.admin.purchaseRequests.approve.useMutation({ onSuccess:()=>{toast.success("تم اعتماد الطلب");refetch();},onError:e=>toast.error(e.message)});
  const rejectPurchase = trpc.admin.purchaseRequests.reject.useMutation({ onSuccess:()=>{toast.success("تم رفض الطلب");setReason("");setSelected(null);refetch();},onError:e=>toast.error(e.message)});
  const cancelPurchase = trpc.admin.purchaseRequests.cancel.useMutation({ onSuccess:()=>{toast.success("تم إلغاء طلب الشراء");setReason("");setSelected(null);refetch();},onError:e=>toast.error(e.message)});
  const approveDeposit = trpc.admin.walletDeposits.approve.useMutation({ onSuccess:()=>{toast.success("تم اعتماد الإيداع وإضافة الرصيد");refetch();},onError:e=>toast.error(e.message)});
  const rejectDeposit = trpc.admin.walletDeposits.reject.useMutation({ onSuccess:()=>{toast.success("تم رفض الإيداع");setReason("");setSelected(null);refetch();},onError:e=>toast.error(e.message)});
  const cancelDeposit = trpc.admin.walletDeposits.cancel.useMutation({ onSuccess:()=>{toast.success("تم إلغاء طلب الإيداع");setReason("");setSelected(null);refetch();},onError:e=>toast.error(e.message)});
  const pendingPurchases = data?.purchaseRequests?.filter(x=>x.status === "pending") ?? [];
  const pendingDeposits = data?.deposits?.filter(x=>x.status === "pending") ?? [];
  const revenueByCurrency = useMemo(()=>{ const m:Record<string,number>={}; for(const r of data?.revenue ?? []) m[r.currency]=(m[r.currency]||0)+Number(r.total||0); return Object.entries(m).map(([c,v])=>`${v.toFixed(2)} ${c}`).join(" · ") || "0.00"; },[data]);
  const [settings, setSettings] = useState<Record<string,string>>({});
  const { data: paymentMethods, refetch: refetchPaymentMethods } = trpc.admin.paymentMethods.list.useQuery(undefined, { enabled: user?.role === "admin" });
  const [paymentForm, setPaymentForm] = useState({ id: 0, name: "", accountNumber: "", accountName: "", accountImageKey: "", accountImageUrl: "", sortOrder: 0, active: true });
  const paymentUpload = trpc.admin.paymentMethods.createUpload.useMutation();
  const createPaymentMethod = trpc.admin.paymentMethods.create.useMutation({ onSuccess:()=>{toast.success("تمت إضافة طريقة الدفع");setPaymentForm({id:0,name:"",accountNumber:"",accountName:"",accountImageKey:"",accountImageUrl:"",sortOrder:0,active:true});refetchPaymentMethods();}, onError:e=>toast.error(e.message)});
  const updatePaymentMethod = trpc.admin.paymentMethods.update.useMutation({ onSuccess:()=>{toast.success("تم تحديث طريقة الدفع");setPaymentForm({id:0,name:"",accountNumber:"",accountName:"",accountImageKey:"",accountImageUrl:"",sortOrder:0,active:true});refetchPaymentMethods();}, onError:e=>toast.error(e.message)});
  const removePaymentMethod = trpc.admin.paymentMethods.remove.useMutation({ onSuccess:()=>{toast.success("تمت إزالة طريقة الدفع");refetchPaymentMethods();}, onError:e=>toast.error(e.message)});
  const updateSettings = trpc.admin.settings.update.useMutation({onSuccess:()=>{toast.success("تم حفظ الإعدادات");refetch();},onError:e=>toast.error(e.message)});
  if (loading || isLoading) return <DashboardLayout><div className="p-8 text-white">جاري تحميل لوحة الإدارة...</div></DashboardLayout>;
  if (!user || user.role !== "admin") return <DashboardLayout><div className="p-8 text-red-300">غير مصرح لك بالدخول.</div></DashboardLayout>;
  const set = (key:string) => settings[key] ?? data?.settings?.[key] ?? "";
  return <DashboardLayout><div dir="rtl" className="space-y-6">
    <div><h1 className="text-white text-3xl font-black">لوحة إدارة MADAR</h1><p className="text-slate-500 mt-1">إدارة المشتريات، المحافظ، الإيداعات، الصرف والإيرادات من مكان واحد.</p></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <Kpi icon={Users} label="المستخدمون" value={data?.users?.length ?? 0}/><Kpi icon={Globe} label="المواقع" value={data?.sites?.length ?? 0}/><Kpi icon={Receipt} label="طلبات شراء معلقة" value={pendingPurchases.length}/><Kpi icon={Wallet} label="إيداعات معلقة" value={pendingDeposits.length}/>
    </div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Kpi icon={RefreshCcw} label="إيرادات MADAR" value={revenueByCurrency}/><Kpi icon={ShieldCheck} label="طلبات شراء مكتملة" value={data?.purchaseRequests?.filter(x=>x.status === "completed").length ?? 0}/><Kpi icon={Wallet} label="رسوم التحويل" value={data?.revenue?.filter(r=>r.type === "conversion_fee").map(r=>`${r.total} ${r.currency}`).join(" · ") || "0.00"}/><Kpi icon={Wallet} label="أرصدة المحافظ" value={(data?.walletTotals||[]).map(r=>`${r.total} ${r.currency}`).join(" · ") || "0.00"}/></div>
    <div className="flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-white/[0.02] p-1">{([['overview','الرئيسية'],['purchases','طلبات شراء المواقع'],['deposits','طلبات الإيداع'],['users','المستخدمون'],['sites','المواقع'],['payments','طرق الدفع'],['settings','الإعدادات']] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-2.5 rounded-xl whitespace-nowrap text-sm font-semibold ${tab===id?'bg-[#6C3CE1] text-white':'text-slate-400 hover:text-white'}`}>{label}</button>)}</div>
    {tab === "overview" && <div className="grid lg:grid-cols-2 gap-6"><Panel title="أحدث طلبات الشراء">{data?.purchaseRequests?.slice(0,8).map(r=><Row key={r.id} title={`طلب #${r.id} — ${r.fullName}`} meta={`${r.amount} ${r.currency}`} status={r.status}/>)}</Panel><Panel title="أحدث الإيداعات">{data?.deposits?.slice(0,8).map(r=><Row key={r.id} title={`إيداع #${r.id}`} meta={`${r.amount} ${r.currency} — ${r.txId}`} status={r.status}/>)}</Panel></div>}
    {tab === "purchases" && <Panel title="طلبات شراء المواقع"><div className="space-y-3">{data?.purchaseRequests?.map(r=><div key={r.id} className="rounded-2xl border border-white/10 bg-white/[0.02] p-4 flex flex-wrap justify-between gap-4"><div><div className="text-white font-bold">#{r.id} — {r.fullName}</div><div className="text-slate-400 text-sm">{r.email} · {r.whatsapp}{r.phone?` · ${r.phone}`:""}</div><div className="text-slate-500 text-xs mt-1">{r.amount} {r.currency} · {new Date(r.createdAt).toLocaleString("ar-SA")}</div></div><div className="flex items-center gap-2"><StatusBadge status={r.status}/>{r.status === "pending" && <><button onClick={()=>approvePurchase.mutate({id:r.id})} className="p-2 rounded-lg bg-emerald-500/15 text-emerald-300"><Check size={16}/></button><button onClick={()=>setSelected(r.id)} className="p-2 rounded-lg bg-red-500/15 text-red-300" title="إلغاء"><X size={16}/></button></>}</div></div>)}</div></Panel>}
    {tab === "deposits" && <Panel title="طلبات شحن المحفظة"><div className="space-y-3">{data?.deposits?.map(r=><div key={r.id} className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><div className="flex flex-wrap justify-between gap-4"><div><div className="text-white font-bold">إيداع #{r.id} — {r.amount} {r.currency}</div><div className="text-cyan-300 text-xs mt-1">طريقة الدفع: {r.paymentMethod?.name || "—"}</div><div className="text-slate-400 text-sm">TxID: <span dir="ltr">{r.txId}</span></div><div className="text-slate-500 text-xs mt-1">{new Date(r.createdAt).toLocaleString("ar-SA")}</div></div><div className="flex items-center gap-2"><StatusBadge status={r.status}/>{r.status === "pending" && <><a href={r.screenshotUrl} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-lg border border-white/10 text-slate-300 text-sm">الإثبات</a><button onClick={()=>approveDeposit.mutate({id:r.id})} className="p-2 rounded-lg bg-emerald-500/15 text-emerald-300"><Check size={16}/></button><button onClick={()=>setSelected(r.id)} className="p-2 rounded-lg bg-red-500/15 text-red-300" title="إلغاء"><X size={16}/></button></>}</div></div>{r.note && <div className="mt-3 text-sm text-slate-400">{r.note}</div>}</div>)}</div></Panel>}
    {tab === "users" && <Panel title="المستخدمون"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-slate-500 border-b border-white/10"><th className="p-3 text-right">#</th><th className="p-3 text-right">الاسم</th><th className="p-3 text-right">البريد</th><th className="p-3 text-right">الدور</th></tr></thead><tbody>{data?.users?.map(u=><tr key={u.id} className="border-b border-white/5"><td className="p-3 text-slate-500">{u.id}</td><td className="p-3 text-white">{u.name||"—"}</td><td className="p-3 text-slate-400">{u.email||"—"}</td><td className="p-3 text-slate-400">{u.role}</td></tr>)}</tbody></table></div></Panel>}
    {tab === "sites" && <Panel title="المواقع"><div className="grid md:grid-cols-2 gap-3">{data?.sites?.map(s=><div key={s.id} className="rounded-xl border border-white/10 p-4"><div className="text-white font-semibold">{s.name}</div><div className="text-slate-500 text-sm" dir="ltr">{s.subdomain}.madar.app</div><StatusBadge status={s.publishStatus}/></div>)}</div></Panel>}
    {tab === "payments" && <Panel title="طرق الدفع"><div className="grid lg:grid-cols-[1fr_1.4fr] gap-6">
      <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-5 space-y-4"><div className="flex items-center justify-between"><div><h3 className="text-white font-bold">{paymentForm.id ? "تعديل طريقة الدفع" : "إضافة طريقة دفع"}</h3><p className="text-slate-500 text-xs mt-1">اسم، صورة الحساب، رقم الحساب، واسم اختياري.</p></div><CreditCard className="text-cyan-300"/></div>
      <input value={paymentForm.name} onChange={e=>setPaymentForm(v=>({...v,name:e.target.value}))} placeholder="اسم طريقة الدفع" className="w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-white"/>
      <input value={paymentForm.accountNumber} onChange={e=>setPaymentForm(v=>({...v,accountNumber:e.target.value}))} placeholder="رقم الحساب" className="w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-white"/>
      <input value={paymentForm.accountName} onChange={e=>setPaymentForm(v=>({...v,accountName:e.target.value}))} placeholder="اسم الحساب (اختياري)" className="w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-white"/>
      <input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const meta=await paymentUpload.mutateAsync({fileName:f.name,contentType:f.type as any,sizeBytes:f.size});await fetch(meta.uploadUrl,{method:"PUT",headers:{"Content-Type":f.type},body:f});setPaymentForm(v=>({...v,accountImageKey:meta.key,accountImageUrl:meta.publicUrl}));toast.success("تم رفع صورة الحساب")}catch(err:any){toast.error(err?.message||"تعذر رفع الصورة")}}} className="w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-slate-300"/>
      {paymentForm.accountImageUrl && <img src={paymentForm.accountImageUrl} className="w-28 h-28 rounded-xl object-cover border border-white/10"/>}
      <div className="flex gap-2"><button disabled={createPaymentMethod.isPending||updatePaymentMethod.isPending} onClick={()=>{const data={name:paymentForm.name,accountNumber:paymentForm.accountNumber,accountName:paymentForm.accountName||undefined,accountImageKey:paymentForm.accountImageKey||undefined,accountImageUrl:paymentForm.accountImageUrl||undefined,sortOrder:paymentForm.sortOrder,active:paymentForm.active}; paymentForm.id ? updatePaymentMethod.mutate({id:paymentForm.id,...data}) : createPaymentMethod.mutate(data)}} className="flex-1 px-4 py-3 rounded-xl bg-[#6C3CE1] text-white font-bold">{paymentForm.id?"حفظ التعديلات":"إضافة طريقة الدفع"}</button>{paymentForm.id&&<button onClick={()=>setPaymentForm({id:0,name:"",accountNumber:"",accountName:"",accountImageKey:"",accountImageUrl:"",sortOrder:0,active:true})} className="px-4 rounded-xl border border-white/10 text-slate-300">إلغاء</button>}</div></div>
      <div className="space-y-3">{!paymentMethods?.length?<div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-slate-500">لا توجد طرق دفع بعد.</div>:paymentMethods.map(m=><div key={m.id} className="rounded-2xl border border-white/10 bg-white/[0.02] p-4 flex flex-wrap items-center gap-4"><div className="w-16 h-16 rounded-xl overflow-hidden border border-white/10 bg-white/5 flex items-center justify-center">{m.accountImageUrl?<img src={m.accountImageUrl} className="w-full h-full object-cover"/>:<CreditCard className="text-slate-500"/>}</div><div className="flex-1 min-w-[180px]"><div className="text-white font-bold">{m.name}</div><div className="text-slate-400 text-sm" dir="ltr">{m.accountNumber}</div>{m.accountName&&<div className="text-slate-500 text-xs">{m.accountName}</div>}<StatusBadge status={m.active?"active":"inactive"}/></div><div className="flex gap-2"><button onClick={()=>setPaymentForm({id:m.id,name:m.name,accountNumber:m.accountNumber,accountName:m.accountName||"",accountImageKey:m.accountImageKey||"",accountImageUrl:m.accountImageUrl||"",sortOrder:m.sortOrder,active:m.active})} className="p-2 rounded-lg bg-cyan-400/10 text-cyan-300" title="تعديل"><Pencil size={16}/></button>{m.active&&<button onClick={()=>removePaymentMethod.mutate({id:m.id})} className="p-2 rounded-lg bg-red-500/10 text-red-300" title="إزالة"><Trash2 size={16}/></button>}</div></div>)}</div>
    </div></Panel>}
    {tab === "settings" && <Panel title="إعدادات المنصة"><div className="grid md:grid-cols-2 gap-4">{['site_purchase_enabled','site_purchase_price','site_purchase_currency','exchange_fee_percent','sar_to_try_rate','try_to_sar_rate'].map(key=><label key={key} className="space-y-2"><span className="text-slate-400 text-sm">{key}</span><input defaultValue={set(key)} onChange={e=>setSettings(v=>({...v,[key]:e.target.value}))} className="w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-white"/></label>)}</div><button onClick={()=>updateSettings.mutate(settings)} className="mt-5 px-5 py-3 rounded-xl bg-[#6C3CE1] text-white font-bold">حفظ الإعدادات</button></Panel>}
    {selected !== null && <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0B1124] p-5"><h3 className="text-white font-bold text-lg">إلغاء الطلب</h3><textarea value={reason} onChange={e=>setReason(e.target.value)} className="w-full min-h-32 mt-4 rounded-xl border border-white/10 bg-white/[0.04] p-3 text-white" placeholder="سبب الإلغاء (اختياري)..."/><div className="flex gap-2 mt-4"><button onClick={()=>{ if(tab==='purchases') cancelPurchase.mutate({id:selected,reason:reason||undefined}); else cancelDeposit.mutate({id:selected,reason:reason||undefined}); }} className="flex-1 rounded-xl bg-red-500/20 text-red-300 py-3 font-bold">تأكيد الإلغاء</button><button onClick={()=>{setSelected(null);setReason("")}} className="flex-1 rounded-xl border border-white/10 text-slate-300 py-3">إلغاء</button></div></div></div>}
  </div></DashboardLayout>;
}
function Kpi({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><Icon className="text-cyan-300 mb-3" size={20}/><div className="text-slate-500 text-xs">{label}</div><div className="text-white text-2xl font-black mt-1">{value}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="text-white font-bold mb-4">{title}</h2>{children}</section>}
function Row({title,meta,status}:{title:string;meta:string;status:string}){return <div className="flex justify-between gap-3 py-3 border-b border-white/5"><div><div className="text-white text-sm font-semibold">{title}</div><div className="text-slate-500 text-xs">{meta}</div></div><StatusBadge status={status}/></div>}
